### ISSUE TITLE
Publishing the IRB docs?

### ISSUE THREAD

**Issue by Daniel-Mietchen** [CBMIWU/Research_Reproducibility#2]
In her RDA talk (cf. #1), Leslie briefly touched upon the IRB approval process for the project. I am working on making more of these procedures open, so I was wondering whether you would be interested in sharing the docs relating to your approval.

**Comment by datadiva** [comment]
The slides can be found at http://bit.ly/2cnWorU
Great question on the IRB process. I'll contact you offline for a discussion on it.

**Comment by Daniel-Mietchen** [comment]
I haven't seen any contact from your end, so I'll just reiterate that I remain interested.

**Comment by datadiva** [comment]
As we have contacted through LinkedIn a week ago, I would consider this contact and am closing this comment.
